### ISSUE TITLE
Printing of a title longer than 60 characters fails and produces warning

### ISSUE THREAD

**Issue by Andros-Spica** [Archaeology-ABM/nassa-hs#6]
Printing of a title longer than 58 characters fails and produces the warning:

`nassa-Windows.exe: <stdout>: commitBuffer: invalid argument (invalid character)`

Full title (90 characters): "Module name or title. It must include a useful description of module. Max. 100 characters."

Full title :
![image](https://user-images.githubusercontent.com/4660541/156393338-500c9166-9223-40c3-9a8b-a9e0b8410b15.png)

Shorter title (58 characters):
![image](https://user-images.githubusercontent.com/4660541/156393506-21f3b605-1539-48b5-b483-206080328c32.png)

**Comment by nevrome** [comment]
Upon closer inspection I realized that the issue is most likely caused by the [`…` character used by table-layout](https://hackage.haskell.org/package/table-layout-0.9.1.0/docs/src/Text.Layout.Table.Spec.CutMark.html#singleCutMark). I replaced that now in v0.4.1. Please reopen if the issue is not fixed.
